### ISSUE TITLE
わかりにくい表現

### ISSUE THREAD

**Issue by lonesometraveler** [garasubo/embedded-book#2]
１章の以下の以下の部分、

> もっとも汎用OSと組込みOSの厳密な区別はなく、最近は強力な組込み機器向けのCPUも多く存在するため、Linuxが組込み機器に使われるケースもあります。
そのため、必ずしも上記のような性質が汎用OSと同じ程度ということもあります。

「そのため、」以下の１文がわかりにくくないでしょうか。

**Comment by garasubo** [comment]
224bd0a で対処しました
